version: '3.8'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network  # Ensure FastAPI is part of the app network

  react:
    build:
      context: ./image-crud
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - fastapi
    env_file:
      - ./image-crud/.env
    networks:
      - app-network  # Ensure React is part of the app network

networks:
  app-network:  # Define the shared network
    driver: bridge
